name: Publish To Local Server

on:
 push:
  branches: ["master"]
 

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish To Local Server
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy To IIS 
        shell: powershell
        run: |
            try{
              Stop-WebAppPool -Name "TestingLearnings"
              Start-Sleep -Seconds 3
              Write-Host "Application Pool dayandırıldı."
            } catch {
              Write-Host "Application Pool bulunamadı veya zaten durdurulmuş."
            }
            #copy files to IIS directory
            Copy-Item -Path "./publish/*" -Destination "C:\inetpub\wwwroot\TicketApp" -Recurse -Force
            Write-Host "Yeni fayllar uğurla kopyalandı."


            try{
              Start-WebAppPool -Name "TestingLearnings"
              Write-Host "Application Pool işə salındı."
            } catch {
              Write-Host "Application Pool işə salınmadı."
            }
